//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
// 
namespace osdrmWallet.osdrmh2kLIS1 {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="opensdrmwsBinding", Namespace="http://www.adetti.pt/opensdrmws")]
    public class opensdrmws : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public opensdrmws() {
            this.Url = "http://localhost/opensdrm/h2kLIS/LIS.ws.php";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/opensdrm/h2kLIS/LIS.ws.php/LISrequestContentKeyStore", RequestNamespace="http://www.adetti.pt/opensdrmws", ResponseNamespace="http://www.adetti.pt/opensdrmws")]
        [return: System.Xml.Serialization.SoapElementAttribute("result_msg")]
        public string LISrequestContentKeyStore(string key_list, string cid) {
            object[] results = this.Invoke("LISrequestContentKeyStore", new object[] {
                        key_list,
                        cid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLISrequestContentKeyStore(string key_list, string cid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LISrequestContentKeyStore", new object[] {
                        key_list,
                        cid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndLISrequestContentKeyStore(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/opensdrm/h2kLIS/LIS.ws.php/LISrequestLicenseDownload", RequestNamespace="http://www.adetti.pt/opensdrmws", ResponseNamespace="http://www.adetti.pt/opensdrmws")]
        [return: System.Xml.Serialization.SoapElementAttribute("msg")]
        public string LISrequestLicenseDownload(string uid, string cid, string authdata, out string license) {
            object[] results = this.Invoke("LISrequestLicenseDownload", new object[] {
                        uid,
                        cid,
                        authdata});
            license = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLISrequestLicenseDownload(string uid, string cid, string authdata, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LISrequestLicenseDownload", new object[] {
                        uid,
                        cid,
                        authdata}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndLISrequestLicenseDownload(System.IAsyncResult asyncResult, out string license) {
            object[] results = this.EndInvoke(asyncResult);
            license = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/opensdrm/h2kLIS/LIS.ws.php/LISrequestLicenseDelete", RequestNamespace="http://www.adetti.pt/opensdrmws", ResponseNamespace="http://www.adetti.pt/opensdrmws")]
        [return: System.Xml.Serialization.SoapElementAttribute("msg")]
        public string LISrequestLicenseDelete(string uid, string cid) {
            object[] results = this.Invoke("LISrequestLicenseDelete", new object[] {
                        uid,
                        cid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLISrequestLicenseDelete(string uid, string cid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LISrequestLicenseDelete", new object[] {
                        uid,
                        cid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndLISrequestLicenseDelete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/opensdrm/h2kLIS/LIS.ws.php/LISrequestLicenseCreation", RequestNamespace="http://www.adetti.pt/opensdrmws", ResponseNamespace="http://www.adetti.pt/opensdrmws")]
        [return: System.Xml.Serialization.SoapElementAttribute("msg")]
        public string LISrequestLicenseCreation(string uid, string cid, string licdata) {
            object[] results = this.Invoke("LISrequestLicenseCreation", new object[] {
                        uid,
                        cid,
                        licdata});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLISrequestLicenseCreation(string uid, string cid, string licdata, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LISrequestLicenseCreation", new object[] {
                        uid,
                        cid,
                        licdata}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndLISrequestLicenseCreation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
