/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "Freeamp.h"

#if ( (TC_IMPL_TC_Freeamp_0 == 'F') \
&& (TC_IMPL_TC_Freeamp_1 == 'r') \
&& (TC_IMPL_TC_Freeamp_2 == 'e') \
&& (TC_IMPL_TC_Freeamp_3 == 'e') \
&& (TC_IMPL_TC_Freeamp_4 == 'a') \
&& (TC_IMPL_TC_Freeamp_5 == 'm') \
&& (TC_IMPL_TC_Freeamp_6 == 'p') \
) && !defined(TC_DEF_TC_Freeamp)
#define TC_DEF_TC_Freeamp 1
const struct CORBA_TypeCode_struct TC_Freeamp_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "Freeamp", "IDL:Freeamp:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_string_0 == 'F') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_1 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_2 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_3 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_4 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_5 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_6 == 'p') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_string)
#define TC_DEF_TC_CORBA_sequence_CORBA_string 1
static const CORBA_TypeCode anon_subtypes_array6[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array6,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_string_0 == 'F') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_1 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_2 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_3 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_4 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_5 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_6 == 'p') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_string)
#define TC_DEF_TC_CORBA_sequence_CORBA_string 1
static const CORBA_TypeCode anon_subtypes_array15[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array15,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Freeamp_StringList_0 == 'F') \
&& (TC_IMPL_TC_Freeamp_StringList_1 == 'r') \
&& (TC_IMPL_TC_Freeamp_StringList_2 == 'e') \
&& (TC_IMPL_TC_Freeamp_StringList_3 == 'e') \
&& (TC_IMPL_TC_Freeamp_StringList_4 == 'a') \
&& (TC_IMPL_TC_Freeamp_StringList_5 == 'm') \
&& (TC_IMPL_TC_Freeamp_StringList_6 == 'p') \
) && !defined(TC_DEF_TC_Freeamp_StringList)
#define TC_DEF_TC_Freeamp_StringList 1
static const CORBA_TypeCode anon_subtypes_array19[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_Freeamp_StringList_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "StringList", "IDL:Freeamp/StringList:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array19,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (ORBIT_IMPL_CORBA_sequence_CORBA_string_0 == 'F') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_1 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_2 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_3 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_4 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_5 == 'm') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_6 == 'p') \
) && !defined(ORBIT_DEF_CORBA_sequence_CORBA_string)
#define ORBIT_DEF_CORBA_sequence_CORBA_string 1

gpointer
CORBA_sequence_CORBA_string__free(gpointer mem, gpointer dat,
				  CORBA_boolean free_strings)
{
   CORBA_sequence_CORBA_string *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_CORBA_string *
CORBA_sequence_CORBA_string__alloc(void)
{
   CORBA_sequence_CORBA_string *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CORBA_string),
		  (ORBit_free_childvals) CORBA_sequence_CORBA_string__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

CORBA_char **
CORBA_sequence_CORBA_string_allocbuf(CORBA_unsigned_long len)
{
   CORBA_char **retval =
      ORBit_alloc(sizeof(CORBA_char *) * len,
		  (ORBit_free_childvals) CORBA_string__free,

		  GUINT_TO_POINTER(len));
   memset(retval, '\0', sizeof(CORBA_char *) * len);
   return retval;
}
#endif

gpointer
Freeamp_StringList__free(gpointer mem, gpointer dat,
			 CORBA_boolean free_strings)
{
   return CORBA_sequence_CORBA_string__free(mem, dat, free_strings);
}

Freeamp_StringList *
Freeamp_StringList__alloc(void)
{
   return CORBA_sequence_CORBA_string__alloc();
}

CORBA_unsigned_long Freeamp__classid = 0;
