/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "Freeamp.h"

void
_ORBIT_skel_Freeamp_TogglePause(POA_Freeamp * _ORBIT_servant,
				GIOPRecvBuffer * _ORBIT_recv_buffer,
				CORBA_Environment * ev,
				void (*_impl_TogglePause)
				(PortableServer_Servant _servant,
				 CORBA_Environment * ev))
{
   _impl_TogglePause(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Freeamp_Previous(POA_Freeamp * _ORBIT_servant,
			     GIOPRecvBuffer * _ORBIT_recv_buffer,
			     CORBA_Environment * ev,
			     void (*_impl_Previous) (PortableServer_Servant
						     _servant,
						     CORBA_Environment * ev))
{
   _impl_Previous(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Freeamp_Next(POA_Freeamp * _ORBIT_servant,
			 GIOPRecvBuffer * _ORBIT_recv_buffer,
			 CORBA_Environment * ev,
			 void (*_impl_Next) (PortableServer_Servant _servant,
					     CORBA_Environment * ev))
{
   _impl_Next(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Freeamp_Quit(POA_Freeamp * _ORBIT_servant,
			 GIOPRecvBuffer * _ORBIT_recv_buffer,
			 CORBA_Environment * ev,
			 void (*_impl_Quit) (PortableServer_Servant _servant,
					     CORBA_Environment * ev))
{
   _impl_Quit(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Freeamp_Play(POA_Freeamp * _ORBIT_servant,
			 GIOPRecvBuffer * _ORBIT_recv_buffer,
			 CORBA_Environment * ev,
			 void (*_impl_Play) (PortableServer_Servant _servant,
					     CORBA_Environment * ev))
{
   _impl_Play(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Freeamp_Stop(POA_Freeamp * _ORBIT_servant,
			 GIOPRecvBuffer * _ORBIT_recv_buffer,
			 CORBA_Environment * ev,
			 void (*_impl_Stop) (PortableServer_Servant _servant,
					     CORBA_Environment * ev))
{
   _impl_Stop(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Freeamp_AddSong(POA_Freeamp * _ORBIT_servant,
			    GIOPRecvBuffer * _ORBIT_recv_buffer,
			    CORBA_Environment * ev,
			    void (*_impl_AddSong) (PortableServer_Servant
						   _servant,
						   const CORBA_char * url,
						   CORBA_Environment * ev))
{
   CORBA_char *url;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_2;
      CORBA_unsigned_long _ORBIT_tmpvar_3;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (_ORBIT_tmpvar_3))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 url = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(url[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_3 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 url = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(url[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      }
   }
   _impl_AddSong(_ORBIT_servant, url, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Freeamp_PlayNumber(POA_Freeamp * _ORBIT_servant,
			       GIOPRecvBuffer * _ORBIT_recv_buffer,
			       CORBA_Environment * ev,
			       void (*_impl_PlayNumber)
			       (PortableServer_Servant _servant,
				const CORBA_char * number,
				CORBA_Environment * ev))
{
   CORBA_char *number;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_2;
      CORBA_unsigned_long _ORBIT_tmpvar_3;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (_ORBIT_tmpvar_3))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 number = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(number[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_3 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 number = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(number[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      }
   }
   _impl_PlayNumber(_ORBIT_servant, number, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Freeamp_GetPlaylist(POA_Freeamp * _ORBIT_servant,
				GIOPRecvBuffer * _ORBIT_recv_buffer,
				CORBA_Environment * ev,
				void (*_impl_GetPlaylist)
				(PortableServer_Servant _servant,
				 Freeamp_StringList ** list,
				 CORBA_Environment * ev))
{
   Freeamp_StringList *list;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
      } else {
      }
   }
   _impl_GetPlaylist(_ORBIT_servant, &(list), ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    register CORBA_unsigned_long _ORBIT_tmpvar_0;
	    register CORBA_unsigned_long _ORBIT_tmpvar_1;
	    CORBA_unsigned_long _ORBIT_tmpvar_2;

	    giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					     (_ORBIT_send_buffer), 4);
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof((*list)._length));
	       memcpy(_ORBIT_t, &((*list)._length), sizeof((*list)._length));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof((*list)._length));
	    }
	    for (_ORBIT_tmpvar_0 = 0; _ORBIT_tmpvar_0 < (*list)._length;
		 _ORBIT_tmpvar_0++) {
	       _ORBIT_tmpvar_2 = strlen((*list)._buffer[_ORBIT_tmpvar_0]) + 1;
	       giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
						(_ORBIT_send_buffer), 4);
	       {
		  guchar *_ORBIT_t;

		  _ORBIT_t = alloca(sizeof(_ORBIT_tmpvar_2));
		  memcpy(_ORBIT_t, &(_ORBIT_tmpvar_2),
			 sizeof(_ORBIT_tmpvar_2));
		  giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
						 (_ORBIT_send_buffer),
						 (_ORBIT_t),
						 sizeof(_ORBIT_tmpvar_2));
	       }
	       {
		  guchar *_ORBIT_t;

		  _ORBIT_t =
		     alloca(sizeof
			    ((*list).
			     _buffer[_ORBIT_tmpvar_0][_ORBIT_tmpvar_1]) *
			    _ORBIT_tmpvar_2);
		     memcpy(_ORBIT_t, ((*list)._buffer[_ORBIT_tmpvar_0]),
			    sizeof((*list).
				   _buffer[_ORBIT_tmpvar_0][_ORBIT_tmpvar_1])
			    * _ORBIT_tmpvar_2);
		  giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
						 (_ORBIT_send_buffer),
						 (_ORBIT_t),
						 sizeof((*list).
							_buffer
							[_ORBIT_tmpvar_0]
							[_ORBIT_tmpvar_1]) *
						 _ORBIT_tmpvar_2);
	       }
	    }

	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
      if (ev->_major == CORBA_NO_EXCEPTION)
	 CORBA_free(list);
   }
}
void
_ORBIT_skel_Freeamp_GetNumber(POA_Freeamp * _ORBIT_servant,
			      GIOPRecvBuffer * _ORBIT_recv_buffer,
			      CORBA_Environment * ev,
			      CORBA_long(*_impl_GetNumber)
			      (PortableServer_Servant _servant,
			       CORBA_Environment * ev))
{
   CORBA_long _ORBIT_retval;

   _ORBIT_retval = _impl_GetNumber(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					     (_ORBIT_send_buffer), 4);
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof(_ORBIT_retval));
	       memcpy(_ORBIT_t, &(_ORBIT_retval), sizeof(_ORBIT_retval));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof(_ORBIT_retval));
	    }
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Freeamp_DeleteNumber(POA_Freeamp * _ORBIT_servant,
				 GIOPRecvBuffer * _ORBIT_recv_buffer,
				 CORBA_Environment * ev,
				 void (*_impl_DeleteNumber)
				 (PortableServer_Servant _servant,
				  const CORBA_long number,
				  CORBA_Environment * ev))
{
   CORBA_long number;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (number))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));} else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 number = *((CORBA_long *) _ORBIT_curptr);
      }
   }
   _impl_DeleteNumber(_ORBIT_servant, number, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
static ORBitSkeleton
get_skel_Freeamp(POA_Freeamp * servant,
		 GIOPRecvBuffer * _ORBIT_recv_buffer, gpointer * impl)
{
   gchar *opname = _ORBIT_recv_buffer->message.u.request.operation;

   switch (opname[0]) {
     case 'A':
	if (strcmp((opname + 1), "ddSong"))
	   break;
	*impl = (gpointer) servant->vepv->Freeamp_epv->AddSong;
	return (ORBitSkeleton) _ORBIT_skel_Freeamp_AddSong;
	break;
     case 'D':
	if (strcmp((opname + 1), "eleteNumber"))
	   break;
	*impl = (gpointer) servant->vepv->Freeamp_epv->DeleteNumber;
	return (ORBitSkeleton) _ORBIT_skel_Freeamp_DeleteNumber;
	break;
     case 'G':
	switch (opname[1]) {
	  case 'e':
	     switch (opname[2]) {
	       case 't':
		  switch (opname[3]) {
		    case 'N':
		       if (strcmp((opname + 4), "umber"))
			  break;
		       *impl =
			  (gpointer) servant->vepv->Freeamp_epv->GetNumber;
		       return (ORBitSkeleton) _ORBIT_skel_Freeamp_GetNumber;
		       break;
		    case 'P':
		       if (strcmp((opname + 4), "laylist"))
			  break;
		       *impl =
			  (gpointer) servant->vepv->Freeamp_epv->GetPlaylist;
		       return (ORBitSkeleton) _ORBIT_skel_Freeamp_GetPlaylist;
		       break;
		    default:
		       break;
		  }
		  break;
	       default:
		  break;
	     }
	     break;
	  default:
	     break;
	}
	break;
     case 'N':
	if (strcmp((opname + 1), "ext"))
	   break;
	*impl = (gpointer) servant->vepv->Freeamp_epv->Next;
	return (ORBitSkeleton) _ORBIT_skel_Freeamp_Next;
	break;
     case 'P':
	switch (opname[1]) {
	  case 'l':
	     switch (opname[2]) {
	       case 'a':
		  switch (opname[3]) {
		    case 'y':
		       switch (opname[4]) {
			 case '\0':
			    *impl =
			       (gpointer) servant->vepv->Freeamp_epv->Play;
			    return (ORBitSkeleton) _ORBIT_skel_Freeamp_Play;
			    break;
			 case 'N':
			    if (strcmp((opname + 5), "umber"))
			       break;
			    *impl =
			       (gpointer) servant->vepv->Freeamp_epv->
			       PlayNumber;
			    return (ORBitSkeleton)
			       _ORBIT_skel_Freeamp_PlayNumber;
			    break;
			 default:
			    break;
		       }
		       break;
		    default:
		       break;
		  }
		  break;
	       default:
		  break;
	     }
	     break;
	  case 'r':
	     if (strcmp((opname + 2), "evious"))
		break;
	     *impl = (gpointer) servant->vepv->Freeamp_epv->Previous;
	     return (ORBitSkeleton) _ORBIT_skel_Freeamp_Previous;
	     break;
	  default:
	     break;
	}
	break;
     case 'Q':
	if (strcmp((opname + 1), "uit"))
	   break;
	*impl = (gpointer) servant->vepv->Freeamp_epv->Quit;
	return (ORBitSkeleton) _ORBIT_skel_Freeamp_Quit;
	break;
     case 'S':
	if (strcmp((opname + 1), "top"))
	   break;
	*impl = (gpointer) servant->vepv->Freeamp_epv->Stop;
	return (ORBitSkeleton) _ORBIT_skel_Freeamp_Stop;
	break;
     case 'T':
	if (strcmp((opname + 1), "ogglePause"))
	   break;
	*impl = (gpointer) servant->vepv->Freeamp_epv->TogglePause;
	return (ORBitSkeleton) _ORBIT_skel_Freeamp_TogglePause;
	break;
     default:
	break;
   }
   return NULL;
}

static void
init_local_objref_Freeamp(CORBA_Object obj, POA_Freeamp * servant)
{
   obj->vepv[Freeamp__classid] = servant->vepv->Freeamp_epv;
}

void
POA_Freeamp__init(PortableServer_Servant servant, CORBA_Environment * env)
{
   static const PortableServer_ClassInfo class_info =
      { (ORBit_impl_finder) & get_skel_Freeamp, "IDL:Freeamp:1.0",
	 (ORBit_local_objref_init) & init_local_objref_Freeamp };

   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   ORBIT_OBJECT_KEY(((PortableServer_ServantBase *) servant)->_private)->
      class_info = (PortableServer_ClassInfo *) & class_info;
   if (!Freeamp__classid)
      Freeamp__classid = ORBit_register_class(&class_info);
}

void
POA_Freeamp__fini(PortableServer_Servant servant, CORBA_Environment * env)
{
   PortableServer_ServantBase__fini(servant, env);
}
