//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by zinfui.rc
//
#define IDI_EXE_ICON                    101
#define IDC_URL                         101
#define IDB_DIALS                       104
#define IDC_DIAL                        104
#define IDI_INFO                        104
#define IDB_CONTROL_MASK_MID            105
#define IDB_MID                         111
#define IDB_LEFT                        112
#define IDB_RIGHT                       113
#define IDB_BIG_FONT                    117
#define IDB_SMALL_FONT                  118
#define IDB_LOGO                        119
#define IDB_RIGHT_256                   121
#define IDB_MID_256                     122
#define IDB_LEFT_256                    123
#define IDB_DIALS_256                   124
#define IDB_SMALL_FONT_256              127
#define IDB_LOGO_256                    128
#define IDB_BIG_FONT_256                129
#define IDB_LAST                        130
#define IDB_NEXT                        131
#define IDB_PAUSE                       132
#define IDB_PLAY                        133
#define IDB_STOP                        134
#define IDB_CLOSE                       135
#define IDB_MINIMIZE                    136
#define IDB_MODE                        137
#define IDB_STOP_256                    138
#define IDB_LAST_256                    139
#define IDB_MINIMIZE_256                140
#define IDB_MODE_256                    141
#define IDB_NEXT_256                    142
#define IDB_PAUSE_256                   143
#define IDB_PLAY_256                    144
#define IDB_CLOSE_256                   145
#define IDB_OPEN                        146
#define IDB_REPEAT                      147
#define IDB_SHUFFLE                     148
#define IDB_SHUFFLE_256                 149
#define IDB_REPEAT_256                  150
#define IDB_OPEN_256                    151
#define IDB_COLORS                      152
#define IDB_SHUFFLED_ICON_256           153
#define IDB_REPEAT_ALL_ICON_256         154
#define IDB_REPEAT_ICON                 155
#define IDB_REPEAT_ICON_256             156
#define IDB_SHUFFLED_ICON               157
#define IDB_REPEAT_ALL_ICON             158
#define IDB_WINDOW_MASK_MID             159
#define IDB_BODY                        160
#define IDB_BODY256                     161
#define IDB_BODY_256                    161
#define IDB_TIME_BACK                   166
#define IDB_DRAWER_MASK                 167
#define IDB_DRAWER                      168
#define IDB_PLAYLIST_BODY               169
#define IDB_PLAYLIST_CONTROL_MASK       170
#define IDB_PANEL_BACKING_MASK          171
#define IDB_PANEL_BACKING               172
#define IDB_TITLE_BACK                  173
#define IDB_SCROLLBAR                   174
#define IDB_TIME_BACK_256               176
#define IDB_SCROLLBAR_256               177
#define IDB_PANEL_BACKING_256           178
#define IDB_PLAYLIST_BODY_256           179
#define IDB_DRAWER_256                  180
#define IDB_DELETE_256                  182
#define IDB_ADD_256                     183
#define IDB_DELETE                      184
#define IDB_ADD                         185
#define IDB_SAVE_256                    186
#define IDB_LOAD_256                    187
#define IDB_SAVE                        188
#define IDB_LOAD                        189
#define IDM_MAIN                        191
#define IDM_TRAY                        192
#define IDD_PREF                        193
#define IDD_PREF1                       193
#define IDD_PREF_GENERAL                193
#define IDD_MAIN_PREF_DIALOG            195
#define IDD_PREF_PROFILE                199
#define IDB_FOLDER                      200
#define IDR_CONTEXT                     201
#define IDD_OPENURL                     219
#define IDD_SAVERIO                     220
#define IDD_UPDATEAVAILABLE             220
#define IDD_PREF3                       221
#define IDD_PREF_DEBUG                  221
#define IDD_PREF2                       223
#define IDD_PREF_STREAMING              223
#define IDD_PREF4                       224
#define IDD_PREF_ABOUT                  224
#define IDD_PREF5                       225
#define IDD_PREF_THEME                  225
#define IDD_PREF6                       226
#define IDD_PREF_UPDATE                 226
#define IDD_PREF_GENERAL_OLD            227
#define IDD_PREF_ADVANCED               233
#define IDD_PREF_PLUGINS                234
#define IDD_PREF_DIRECTORY              235
#define IDD_PREF_BROWSER                236
#define IDD_PREF_CDAUDIO                237
#define IDB_CHECKED                     542
#define IDB_UNCHECKED                   543
#define IDC_FADE                        1001
#define IDC_SAVE_RIO                    1002
#define IDC_UI                          1005
#define IDC_APPLY                       1005
#define IDC_PMO                         1006
#define IDC_HELPME                      1006
#define IDC_PRIORITY                    1007
#define IDC_INPUT                       1008
#define IDC_LOGOUTPUT                   1009
#define IDC_OUTPUT                      1010
#define IDC_LOG                         1010
#define IDC_STREAM_INTERVAL             1011
#define IDC_LOGINPUT                    1012
#define IDC_LOGDECODER                  1013
#define IDC_PAGE                        1013
#define IDC_LOGPERFORMANCE              1014
#define IDC_TRAY                        1015
#define IDC_LOGMAIN                     1015
#define IDC_SAVESTREAMS                 1016
#define IDC_STAYONTOP                   1017
#define IDC_STREAMSAVEDIR               1017
#define IDC_BROWSE                      1018
#define IDC_SAVELOCATION_TEXT           1019
#define IDC_PORT                        1020
#define IDC_SAVEMUSICDIR                1020
#define IDC_PROXYADDRESS_TEXT           1021
#define IDC_PORT_TEXT                   1022
#define IDC_USEPROXY                    1023
#define IDC_PROXYADDRESS                1024
#define IDC_COLON_TEXT                  1025
#define IDC_PREBUFFER                   1026
#define IDC_USETHISIP                   1026
#define IDC_IPADDRESS                   1027
#define IDC_IPADDRESS1                  1027
#define IDC_IPADDRESS_TEXT              1028
#define IDC_OPEN_URL                    1029
#define IDC_PERIOD1                     1030
#define IDC_PERIOD2                     1031
#define IDC_IPADDRESS2                  1032
#define IDC_IPADDRESS3                  1033
#define IDC_APP                         1033
#define IDC_IPADDRESS4                  1034
#define IDC_VERSION                     1034
#define IDC_PERIOD3                     1035
#define IDC_GOTOFREEAMP                 1036
#define IDC_GOTOEMUSIC                  1037
#define IDC_CREDIT                      1038
#define IDC_BASED_ON_FREEAMP            1039
#define IDC_THEMELISTBOX                1040
#define IDC_GOTORELATABLE               1040
#define IDC_ADDTHEME                    1041
#define IDC_DELETETHEME                 1042
#define IDC_CHOOSEFONT                  1043
#define IDC_UPDATE                      1044
#define IDC_CHECK                       1045
#define IDC_LIST                        1046
#define IDC_CANCELCHECK                 1047
#define IDC_DESCRIPTION                 1048
#define IDC_STATUS                      1049
#define IDC_AUTOCHECK                   1050
#define IDC_CANCELUPDATE                1051
#define IDC_RECLAIMFILETYPES            1052
#define IDC_ASKRECLAIM                  1053
#define IDC_PORTABLELIST                1054
#define IDC_USEDEFAULTS                 1055
#define IDC_TEXTONLY                    1057
#define IDC_IMAGESONLY                  1058
#define IDC_TEXTANDIMAGES               1059
#define IDC_SAVECURRENTLIST             1060
#define IDC_DEFAULTACTION               1061
#define IDC_UNDERSCORES                 1062
#define IDC_WATCHDIRS                   1063
#define IDC_DIRLIST                     1064
#define IDC_ADD                         1065
#define IDC_ADDDIR                      1065
#define IDC_REMOVEDIR                   1066
#define IDC_PROFILE_LIST                1067
#define IDC_NEW_PROFILE                 1068
#define IDC_ADDPROFILE                  1069
#define IDC_DELETEPROFILE               1070
#define IDC_PROFILE_ENABLE              1071
#define IDC_PROFILE_HELP                1072
#define IDC_AVAILABLE_COLUMN_LIST       1073
#define IDC_CURRENT_COLUMN_LIST         1074
#define IDC_REMOVE_COLUMN               1075
#define IDC_ADD_COLUMN                  1076
#define IDC_UPDATE_AUDIO                1078
#define IDC_MB_URL                      1079
#define IDC_CONTRIBUTE                  1080
#define IDC_CONTRIBUTE_BITZI            1081
#define IDMC_MYMUSIC                    6900
#define IDMC_PLAY                       6901
#define IDMC_STOP                       6902
#define IDMC_PAUSE                      6903
#define IDMC_NEXTTRACK                  6904
#define IDMC_PREVIOUSTRACK              6905
#define IDMC_EXIT                       6906
#define IDMC_FILE                       40013
#define IDMC_SUGGEST                    40014
#define IDMC_BITZILOOKUP                40015
#define IDMC_EDITINFO                   40016
#define IDS_URL                         65535
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         40017
#define _APS_NEXT_CONTROL_VALUE         1081
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
