//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by musicbrowser.rc
//
#define IDS_TOOLBAR                     1
#define IDC_RELATABLE_TEXT2             4
#define IDB_TOOLBAR                     100
#define IDD_MUSICBROWSER                101
#define IDC_URL                         101
#define IDC_SPLITTER                    101
#define IDI_EXE_ICON                    101
#define IDR_MENU1                       102
#define IDI_CLOSED                      104
#define IDC_DRAG                        104
#define IDI_ARROW                       106
#define IDC_NODROP                      106
#define IDI_BLANK                       107
#define IDD_INTROWIZARD_HELLO           107
#define IDI_ACTIVELIST                  109
#define IDR_POPUP                       110
#define IDR_TVPOPUP                     110
#define IDB_PLAYLIST                    113
#define IDB_BITMAP1                     116
#define IDR_TRACKPOPUP                  119
#define IDD_MUSICSEARCH                 120
#define IDR_MENU2                       120
#define IDD_SAVEPLAYLIST                121
#define IDR_LVPOPUP                     121
#define IDR_TVPOPUP1                    122
#define IDR_TVPOPUP2                    123
#define IDB_ALL                         124
#define IDB_UNCATAGORIZED               125
#define IDI_MYMUSIC                     126
#define IDB_PORTABLE                    128
#define IDB_WIZARD                      130
#define IDB_WIZARD_SMALL                131
#define IDB_WIREDPLANET                 132
#define IDB_ICECAST                     133
#define IDB_SHOUTCAST                   134
#define IDB_BUSY                        135
#define IDB_STREAMS                     136
#define IDB_CD                          137
#define IDD_INTROWIZARD_RELATABLE       138
#define IDD_INTROWIZARD_RELATABLETWO    139
#define IDB_RELATABLE                   141
#define IDI_WARN                        207
#define IDD_OPENURL                     219
#define IDD_DELETETRACKS                220
#define IDD_REMOVETRACKS                220
#define IDD_EDITINFO                    259
#define IDD_INTROWIZARD_SEARCH          263
#define IDD_INTROWIZARD_HELLO1          264
#define IDD_MISSINGTRACK                264
#define IDD_FAVORITE                    265
#define IDD_CHECKDB                     266
#define IDB_PLAYING                     542
#define IDB_CATALOG                     543
#define IDB_ARTIST                      544
#define IDB_TRACK                       545
#define IDB_ALBUM                       546
#define IDB_FAVORITES                   547
#define IDC_MUSICTREE                   1000
#define IDC_PLAYLISTBOX                 1002
#define IDC_PLAYLISTCOMBO               1003
#define IDC_SEARCH                      1004
#define IDC_COLLAPSE                    1005
#define IDC_UP                          1006
#define IDC_DELETE                      1007
#define IDC_ADD                         1008
#define IDC_DOWN                        1009
#define IDC_NEWLIST                     1010
#define IDC_SAVELIST                    1010
#define IDC_CLEARLIST                   1011
#define IDC_MUSICCATALOGTEXT            1012
#define IDC_PLAYLISTTEXT                1013
#define IDC_STATUS                      1014
#define IDC_RANDOMIZE                   1015
#define IDC_PLAYLISTNAME                1016
#define IDC_PLAYLISTTITLE               1017
#define IDC_DUMMYCONTROL                1018
#define IDC_LIMITTEXT                   1019
#define IDC_NAME                        1020
#define IDC_YEAR                        1023
#define IDC_SPIN1                       1024
#define IDC_SPINYEAR                    1024
#define IDC_OPEN_URL                    1029
#define IDC_SPIN2                       1029
#define IDC_SPINTRACK                   1029
#define IDC_SHOWHELP                    1030
#define IDC_CAPTION1                    1033
#define IDC_TEXT1                       1034
#define IDC_CAPTION2                    1035
#define IDC_TEXT2                       1036
#define IDC_LOCATIONTEXT                1039
#define IDC_RADIO1                      1040
#define IDC_REMOVE                      1040
#define IDC_RELATABLE_YES               1040
#define IDC_RADIO2                      1041
#define IDC_LOCATE                      1041
#define IDC_DESCRIPTION                 1041
#define IDC_RELATABLE_NO                1041
#define IDC_EDIT1                       1042
#define IDC_PATH                        1042
#define IDC_CHECK                       1042
#define IDC_BUTTON1                     1043
#define IDC_RELATABLE_WEB               1043
#define IDC_BUTTON_MB                   1043
#define IDC_VISIT_BITZI                 1043
#define IDC_RADIO3                      1044
#define IDC_EDIT2                       1045
#define IDC_MISSINGTRACK                1045
#define IDC_BUTTON2                     1046
#define IDC_BITZILOOKUP                 1046
#define IDC_VISIT_MB                    1046
#define IDC_PLAYCOUNT                   1047
#define IDC_RELATABLE_CAPTION1          1049
#define IDC_RELATABLE_TEXT1             1050
#define IDC_RELATABLE_CAPTION2          1051
#define IDC_RELATABLE_CAPTION3          1051
#define IDC_RELATABLE_EDIT1             1052
#define IDC_TEXTTRACK                   1053
#define IDC_BROWSE                      1110
#define IDC_DRIVES                      1231
#define IDC_ALBUM                       1462
#define IDC_ARTIST                      1463
#define IDC_GENRE                       1464
#define IDC_TRACK                       1466
#define IDC_TITLE                       1476
#define IDC_COMMENT                     1477
#define IDC_LOCATION                    1478
#define IDC_DIRECTORY                   1531
#define IDC_CONTRIBUTE_NO               1532
#define IDC_CONTRIBUTE_YES              1533
#define IDD_INTROWIZARD_MUSICBRAINZ     1534
#define IDD_INTROWIZARD_BITZI           1545
#define ID_FILE_NEWPLAYLIST             40001
#define ID_FILE_OPENPLAYLIST            40002
#define ID_FILE_SAVEPLAYLIST            40004
#define ID_FILE_EXIT                    40005
#define ID_FILE_SEARCHFORMUSIC          40007
#define ID_EDIT_VIEWINFO                40008
#define ID_VIEW_MUSICCATALOG            40009
#define ID_SORT_ARTIST                  40010
#define ID_SORT_TITLE                   40011
#define ID_SORT_YEAR                    40012
#define ID_SORT_TRACK                   40013
#define ID_SORT_GENRE                   40014
#define ID_SORT_LENGTH                  40015
#define ID_SORT_LOCATION                40016
#define ID_SORT_RANDOMIZE               40017
#define ID_SORT_ALBUM                   40018
#define ID_FILE_SAVEASPLAYLIST          40019
#define ID_FILE_IMPORT                  40020
#define ID_EDIT_ADDTRACK                40021
#define ID_EDIT_EDIT                    40022
#define ID_EDIT_REMOVE                  40023
#define ID_EDIT_REMOVEFROMDISK          40024
#define ID_EDIT_MOVEUP                  40025
#define ID_EDIT_CLEARPLAYLIST           40027
#define ID_PLAY                         40029
#define ID_POPUP_ADDTRACK_PLAY          40029
#define ID_EDIT                         40031
#define ID_RENAME                       40032
#define ID_ADD                          40033
#define ID_POPUP_ADDTRACK               40033
#define ID_EDIT_MOVEDOWN                40034
#define ID_FILE_EXPORTPLAYLIST          40035
#define ID_EDIT_ADDFILE                 40036
#define ID_EDIT_EDITINFO                40037
#define ID_CONTROLS_PLAYPAUSE           40038
#define ID_CONTROLS_STOP                40039
#define ID_CONTROLS_NEXTSONG            40040
#define ID_CONTROLS_PREVIOUSSONG        40041
#define ID_CONTROLS_SHUFFLE             40043
#define ID_CONTROLS_REPEATNONE          40044
#define ID_CONTROLS_REPEATONE           40045
#define ID_CONTROLS_REPEATALL           40046
#define ID_CONTROLS_MUTE                40047
#define ID_WINDOW_NEXT                  40048
#define ID_WINDOW_PREVIOUS              40049
#define ID_WINDOW_TILEVERTICALLY        40051
#define ID_WINDOW_TILEHORIZONTALLY      40052
#define ID_HELP_CONTENTS                40053
#define ID_HELP_SEARCH                  40054
#define ID_HELP_FREEAMPWEBSITE          40055
#define ID_HELP_EMUSICCOMWEBSITE        40056
#define ID_HELP_ABOUT                   40057
#define ID_VIEW_OPTIONS                 40059
#define ID_EDIT_EDITPLAYLIST            40060
#define ID_FILE_CLOSEPLAYLIST           40061
#define ID_CONTROLS_NORMALORDER         40063
#define ID_POPUP_RENAME                 40065
#define ID_POPUP_REMOVE                 40066
#define ID_POPUP_EDITINFO               40067
#define ID_POPUP_MOVEUP                 40068
#define ID_POPUP_MOVEDOWN               40069
#define ID_POPUP_PLAY                   40070
#define ID_EDIT_UNDO_ACTION             40073
#define ID_EDIT_REDO_ACTION             40074
#define ID_POPUP_EDITPLAYLIST           40075
#define ID_SORT_FILENAME                40076
#define ID_POPUP_EJECT                  40077
#define ID_POPUP_FAVORITE               40079
#define ID_POPUP_EDITSTREAMINFO         40080
#define ID_CONTROLS_EJECT               40081
#define ID_POPUP_REMOVEFAVORITE         40082
#define ID_VIEW_LOCATECURRENTITEM       40083
#define ID_POPUP_ADDTOFAVORITES         40084
#define ID_EDIT_GENERATEPLAYLIST        40085
#define ID_EDIT_SUBMITPLAYLIST          40086
#define ID_EDIT_STARTSIGNATURING        40087
#define ID_SL_QUERY_500                 40088
#define ID_SL_QUERY_1000                40089
#define ID_SL_QUERY_5000                40090
#define ID_SL_QUERY_10000               40091
#define ID_SL_QUERY_20000               40092
#define ID_SL_QUERY_NOMAX               40093
#define ID_POPUP_REFRESH_CD             40095
#define ID_SORT_COMMENT                 40096
#define ID_POPUP_TIP                    40097
#define ID_RELATABLE_EDITPROFILE        40098
#define ID_HELP_RELATABLEWEBSITE        40099
#define ID_POPUP_SUPDATE                40100
#define ID_POPUP_VISITWEB               40101
#define ID_BITZI_LOOKUP                 40102
#define ID_HELP_BITZIWEBSITE            40103
#define IDS_URL                         65535
#define IDC_TRACKTEXT                   65535
#define IDC_TITLETEXT                   65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         40101
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
